### ISSUE TITLE
Unknown exception

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#105]
Here is current exception in the Report View (also in the terminal window): 

```
<asm3.main> 11.631975 - init_gui.py(71): 
Traceback (most recent call last):
  File "/opt/FreeCAD/Ext/freecad/asm3/FCADLogger.py", line 83, in _catch
    return func(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/init_gui.py", line 64, in _contextMenu
    name = cmd.getContextMenuName()
  File "/opt/FreeCAD/Ext/freecad/asm3/gui.py", line 210, in getContextMenuName
    if cls.IsActive() and cls._contextMenuName:
  File "/opt/FreeCAD/Ext/freecad/asm3/gui.py", line 682, in IsActive
    return FreeCADGui.isCommandActive('Std_LinkSelectLinked')
AttributeError: 'module' object has no attribute 'isCommandActive'

<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
Show.TempoVis.isIn3DObject error: Cannot find type information for requested type
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))
<unknown exception traceback><type 'exceptions.SyntaxError'>: ('invalid syntax', ('<string>', 1, 21, '_path_value_temp_ = \n'))

```

I can't exactly remember but it is thrown when I copied `enclosure/Assembly/support`, then dragged and dropped the copy into the Assembly container again.

# Attachments 

[case-v3-20180916T1802.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2386682/case-v3-20180916T1802.zip)

**Comment by realthunder** [comment]
The unknown exception is thrown by Spreadsheet. Are there spreadsheet in the copy? Maybe the spreadsheet copy and paste is now working.
