### ISSUE TITLE
Segfault when run on wayland

### ISSUE THREAD

**Issue by m-sundman** [realthunder/FreeCAD_assembly3#1219]
Stable 2022-04-06 does not work on wayland:
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f8adb0b5520]
#1  /lib/x86_64-linux-gnu/libc.so.6(+0xc01f5) [0x7f8adb1331f5]
#2  /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/./libCoin.so.80(cc_glglue_instance+0x16d) [0x7f8adabd8f7d]
#3  0x7f8add6f7072 in SIM::Coin3D::Quarter::QuarterWidgetP::removeFromCacheContext(QuarterWidgetP_cachecontext*, QOpenGLWidget const*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0xc2
#4  0x7f8add6f711a in SIM::Coin3D::Quarter::QuarterWidgetP::~QuarterWidgetP() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0x1a
#5  0x7f8add6f1ad9 in SIM::Coin3D::Quarter::QuarterWidget::~QuarterWidget() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0xb9
#6  0x7f8add74150a in Gui::View3DInventorViewer::~View3DInventorViewer() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0xa
#7  0x7f8add7230a9 in Gui::View3DInventor::~View3DInventor() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0x179
#8  0x7f8add72321a in Gui::View3DInventor::~View3DInventor() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0xa
#9  0x7f8adb63954e in QObject::event(QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Core.so.5+0x76
#10  0x7f8adbe7807f in QWidget::event(QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Widgets.so.5+0xcc5
#11  0x7f8adbf2234f in QMainWindow::event(QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Widgets.so.5+0xdd
#12  0x7f8adbe4c7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#13  0x7f8adbe5231d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#14  0x7f8add336aa9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0x89
#15  0x7f8adb624606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Core.so.5+0x86
#16  0x7f8adb62483e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Core.so.5+0x1da
#17  0x7f8adb624eb2 in QCoreApplication::exec() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libQt5Core.so.5+0x120
#18  0x7f8add2a6de3 in Gui::Application::runApplication() from /tmp/.mount_FreeCAIZLuzY/usr/bin/../lib/libFreeCADGui.so+0x443
#19  /tmp/.mount_FreeCAIZLuzY/usr/bin/FreeCADLink(+0x46d5) [0x556844e1e6d5]
#20  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f8adb09cd90]
#21  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f8adb09ce40]
#22  /tmp/.mount_FreeCAIZLuzY/usr/bin/FreeCADLink(+0x4a6d) [0x556844e1ea6d]
```

Since even the really big distros are moving, or have already moved, to wayland as default this is a very big problem.

As a workaround this works on **some** systems:
```
$ ./FreeCAD-asm3-Stable.AppImage --appimage-extract
...
$ rm squashfs-root/usr/lib/libstdc*
$ ./appimagetool-x86_64.AppImage squashfs-root
$ rm -r squashfs-root
$ ./FreeCAD_Link_Branch-x86_64.AppImage
```

**Comment by m-sundman** [comment]
Seems fixed.
