### ISSUE TITLE
Image WB, crash

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#1242]
When I try to use an image in the Image WB FreeCAD Linkstage crashes everytime. It works fine in 'official' 0.20

` ~/Downloads/FreeCAD-asm3-Daily-Conda-Py3-Qt5-20220430-glibc2.12-x86_64.AppImage 
/tmp/.mount_FreeCAzCh8uD
FreeCAD 0.20, Libs: 2022.430R26244 +4758 (Git)
Sheet Metal workbench loaded
Assembly4 workbench (v0.11.12) loaded
Initializing Assembly4 workbench (v0.11.12) ............................ done.
<PropShape> PropertyTopoShape.cpp(414): Pending recompute for generating element map: EinhellRails#Body
<PropShape> PropertyTopoShape.cpp(414): Pending recompute for generating element map: EinhellRails#Sketch
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x38920) [0x7f1dbaf6e920]
#1  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x27bf8f) [0x7f1db04c3f8f]
#2  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x2c290b) [0x7f1db050a90b]
#3  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x2b762e) [0x7f1db04ff62e]
#4  /usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x5166fe) [0x7f1db075e6fe]
#5  0x7f1dbd75139d in NaviCubeShared::drawNaviCube(SoCamera*, bool, int, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x13cd
#6  0x7f1dbd7517b6 in NaviCubeImplementation::drawNaviCube(bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x46
#7  0x7f1dbd71ba45 in Gui::View3DInventorViewer::renderScene() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x515
#8  0x7f1dbd6cac0d in SIM::Coin3D::Quarter::QuarterWidget::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x31d
#9  0x7f1dbd6d0ec5 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent(QPaintEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x45
#10  0x7f1dbbf4595d in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x5a3
#11  0x7f1dbbfaedb7 in QFrame::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x27
#12  0x7f1dbc129ebe in QGraphicsView::viewportEvent(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x456
#13  0x7f1dbb4b0019 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0xcd
#14  0x7f1dbbf1a7e1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xcb
#15  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#16  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
#17  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
#18  0x7f1dbbf40612 in QWidgetPrivate::sendPaintEvent(QRegion const&) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x28
#19  0x7f1dbbf40d3f in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x707
#20  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#21  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#22  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#23  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#24  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#25  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#26  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#27  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#28  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#29  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#30  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#31  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#32  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#33  0x7f1dbbf414b1 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2c1
#34  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#35  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#36  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#37  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#38  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#39  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#40  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#41  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#42  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#43  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#44  0x7f1dbbf413ce in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1de
#45  0x7f1dbbf411be in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xb86
#46  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x17ed08) [0x7f1dbbf24d08]
#47  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x17efaf) [0x7f1dbbf24faf]
#48  0x7f1dbbf35dd4 in QWidgetPrivate::syncBackingStore() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x66
#49  0x7f1dbbf45cd9 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x91f
#50  0x7f1dbbff034f in QMainWindow::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdd
#51  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#52  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#53  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
#54  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
#55  0x7f1dbb4b283e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x1da
#56  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5(+0x1dc54c) [0x7f1dbb4e154c]
#57  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f1db7afa76d]
#58  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(+0x56a01) [0x7f1db7afaa01]
#59  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f1db7afaaa1]
#60  0x7f1dbb4e10e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x5e
#61  0x7f1dbb4af019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x187
#62  0x7f1dbc05b8d9 in QDialog::exec() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x11d
#63  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x2d8c71) [0x7f1dbc07ec71]
#64  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so(+0x4b6f22) [0x7f1dbd1c8f22]
#65  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so(+0x382bb4) [0x7f1dbc66cbb4]
#66  0x7f1dbc7a9b5a in App::Application::openDocuments(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0x1bda
#67  0x7f1dbc7aa578 in App::Application::openDocument(char const*, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0xc8
#68  0x7f1dbc7b4508 in App::Application::sOpenDocument(_object*, _object*, _object*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADApp.so+0xe8
#69  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x146f75) [0x7f1dbcac4f75]
#70  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x286) [0x7f1dbcab3dc6]
#71  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x5123) [0x7f1dbcab0e43]
#72  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x12cf99) [0x7f1dbcaaaf99]
#73  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f1dbcaaac51]
#74  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f1dbcaaabfa]
#75  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCode+0x1c) [0x7f1dbcb3d46c]
#76  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x1edaaf) [0x7f1dbcb6baaf]
#77  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(+0x1e9b0c) [0x7f1dbcb67b0c]
#78  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa7) [0x7f1dbcb5f567]
#79  0x7f1dbb85c87c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADBase.so+0x6c
#80  0x7f1dbd2e1305 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x95
#81  0x7f1dbd2e14b1 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x101
#82  0x7f1dbd1c6535 in Gui::Application::open(char const*, char const*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x435
#83  0x7f1dbd2be877 in Gui::RecentFilesAction::activateFile(int) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x257
#84  0x7f1dbd2ead38 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x288
#85  0x7f1dbd2eb1e6 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x146
#86  0x7f1dbb4c8a18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x6c0
#87  0x7f1dbbf18283 in QActionGroup::triggered(QAction*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2f
#88  0x7f1dbb4c8a18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x6c0
#89  0x7f1dbbf15928 in QAction::triggered(bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x32
#90  0x7f1dbbf172b2 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xc6
#91  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x263653) [0x7f1dbc009653]
#92  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x2681a2) [0x7f1dbc00e1a2]
#93  0x7f1dbc00e900 in QMenu::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xbc
#94  0x7f1dbbf454ed in QWidget::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x133
#95  0x7f1dbc00ffac in QMenu::event(QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x2d0
#96  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#97  0x7f1dbbf1ef5e in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x70a
#98  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
#99  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
#100  0x7f1dbbf1e4c4 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x286
#101  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x1aea9d) [0x7f1dbbf54a9d]
#102  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5(+0x1aff7c) [0x7f1dbbf55f7c]
#103  0x7f1dbbf1a7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#104  0x7f1dbbf2031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#105  0x7f1dbd27d5f9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x89
#106  0x7f1dbb4b2606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x86
#107  0x7f1dbba98ec5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x677
#108  0x7f1dbba9991f in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x5f
#109  0x7f1dbba86c65 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Gui.so.5+0x63
#110  /tmp/.mount_FreeCAzCh8uD/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5b010) [0x7f1db21f1010]
#111  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f1db7afa76d]
#112  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(+0x56a01) [0x7f1db7afaa01]
#113  /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f1db7afaaa1]
#114  0x7f1dbb4e10e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x5e
#115  0x7f1dbb4af019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0x187
#116  0x7f1dbb4b2e8f in QCoreApplication::exec() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libQt5Core.so.5+0xfd
#117  0x7f1dbd1ec563 in Gui::Application::runApplication() from /tmp/.mount_FreeCAzCh8uD/usr/bin/../lib/libFreeCADGui.so+0x443
#118  /tmp/.mount_FreeCAzCh8uD/usr/bin/FreeCADLink(+0x470d) [0x55a47e9d270d]
#119  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xcd) [0x7f1dbaf597fd]
#120  /tmp/.mount_FreeCAzCh8uD/usr/bin/FreeCADLink(+0x4aa9) [0x55a47e9d2aa9]
`

`OS: Debian GNU/Linux bookworm/sid (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: Dutch/Netherlands (nl_NL)
`

![IMG_20220603_181153_873](https://user-images.githubusercontent.com/1257901/171991938-7989edf2-f9c0-4308-82c8-39ae47946121.jpeg)
[EinhellRails.FCStd.txt](https://github.com/realthunder/FreeCAD_assembly3/files/8837316/EinhellRails.FCStd.txt)

**Comment by luzpaz** [comment]
Side note: please use code tags when posting errors since hashtags + numbers will trigger an auto-linking to another github ticket.  I've modified the OP to fix that.
