### ISSUE TITLE
FreeCAD Crash (Spreadsheet related)

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#139]
# Last Actions

I was defining some variables in Spreadsheet.

# Is Reproducable? 

I came across with the same case a few times in the last days, but I don't know exact reproduction steps.

# Stack Trace
```
$Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x33060) [0x7ff469d34060]
#1  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1081a4) [0x7ff47255a1a4]
#2  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x10c687) [0x7ff47255e687]
#3  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyGC_Collect+0x28) [0x7ff47255f478]
#4  /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(Py_Finalize+0xf9) [0x7ff472584dd9]
#5  0x7ff472b4c6c3 in Base::InterpreterSingleton::finalize() from /opt/FreeCAD/lib/libFreeCADBase.so+0x21
#6  0x7ff4736a6217 in App::Application::destruct() from /opt/FreeCAD/lib/libFreeCADApp.so+0x2cd
#7  freecad-git(main+0xb47) [0x562380ef6631]
#8  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7ff469d212e1]
#9  freecad-git(_start+0x2a) [0x562380ef596a]
```

# Version 
```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15562 (Git)
Build type: Debug
Branch: LinkStage3
Hash: 35bc149010dc810cdc8428e2756f267a44a4979f
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)
```

**Comment by ceremcem** [comment]
Closing because it's both an old issue and has no clear reproduction steps.
