### ISSUE TITLE
Design In Assembly - Sketcher - Switch between section and full view

### ISSUE THREAD

**Issue by Nemesis81** [realthunder/FreeCAD_assembly3#143]
when editing a sketch from the assembly file. the "Switch between section and full view" function doesn't work with this message in the repor view:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_FreeCAhgze9d/usr/lib/freecad-daily/Mod/Show/TempoVis.py", line 406, in sketchClipPlane
    self.clipPlane(self.allVisibleObjects(sketch), enable, sketch.getGlobalPlacement(), 0.02)
  File "/tmp/.mount_FreeCAhgze9d/usr/lib/freecad-daily/Mod/Show/TempoVis.py", line 365, in clipPlane
    raise ValueError("Document object to be modified does not belong to document TempoVis was made for.")
<type 'exceptions.ValueError'>: Document object to be modified does not belong to document TempoVis was made for.
`
https://youtu.be/rNo95XRllS4

**Comment by ceremcem** [comment]
I would like to note that personally I couldn't understand the issue. Can you please 
1. Include steps to reproduce the problem 
2. Add your build version 
3. Attach the example file

**Comment by realthunder** [comment]
Problem confirmed.

**Comment by ceremcem** [comment]
Sorry, after watching in high resolution, steps were pretty obvious.
