### ISSUE TITLE
graphics crash on 

### ISSUE THREAD

**Issue by J-Dunn** [realthunder/FreeCAD_assembly3#161]
this one probably is graphics related:

```
240.847832 <asm3.sys> sys_slvs.py(49): redundant constraints
0.000177 <asm3.sys> sys_slvs.py(54): dof remaining: 0
0.032878 <asm3.sys> sys_slvs.py(49): redundant constraints
0.000182 <asm3.sys> sys_slvs.py(54): dof remaining: 0
Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x385c0) [0x7f948305d5c0]
#1  /usr/lib64/dri/nouveau_dri.so(+0x59f1b9) [0x7f94762801b9]
#2  /usr/lib64/dri/nouveau_dri.so(+0x46ff4e) [0x7f9476150f4e]
#3  /usr/lib64/dri/nouveau_dri.so(+0x2ade6a) [0x7f9475f8ee6a]
#4  /usr/lib64/dri/nouveau_dri.so(+0x271186) [0x7f9475f52186]
#5  /usr/lib64/dri/nouveau_dri.so(+0x2c60fe) [0x7f9475fa70fe]
#6  /usr/lib64/dri/nouveau_dri.so(+0x1d8720) [0x7f9475eb9720]
#7  /usr/lib64/dri/nouveau_dri.so(+0x1d89e8) [0x7f9475eb99e8]
#8  /usr/lib64/dri/nouveau_dri.so(+0x1d8a73) [0x7f9475eb9a73]
#9  /usr/lib64/dri/nouveau_dri.so(+0x1d8b8d) [0x7f9475eb9b8d]
#10  /usr/lib64/dri/nouveau_dri.so(+0x2c0ff9) [0x7f9475fa1ff9]
#11  /usr/lib64/dri/nouveau_dri.so(+0x2c11c2) [0x7f9475fa21c2]
#12  /usr/lib64/dri/nouveau_dri.so(+0x2c6229) [0x7f9475fa7229]
#13  /usr/lib64/dri/nouveau_dri.so(+0xbc3d8) [0x7f9475d9d3d8]
#14  /usr/lib64/dri/nouveau_dri.so(+0x27b8fd) [0x7f9475f5c8fd]
#15  /usr/lib64/dri/nouveau_dri.so(+0x4638cd) [0x7f94761448cd]
#16  /usr/lib64/dri/nouveau_dri.so(+0x4626d7) [0x7f94761436d7]
#17  /lib64/libGLX_mesa.so.0(+0x49d03) [0x7f9476b31d03]
#18  /lib64/libGLX_mesa.so.0(+0x1d3b1) [0x7f9476b053b1]
#19  0x7f9486cb85a9 in QGLContext::reset() from /lib64/libQtOpenGL.so.4+0x89
#20  0x7f9486c4616c in QGLContext::~QGLContext() from /lib64/libQtOpenGL.so.4+0x5c
#21  0x7f9486c461c2 in QGLContext::~QGLContext() from /lib64/libQtOpenGL.so.4+0x12
#22  0x7f9486c3fbab in QGLWidget::~QGLWidget() from /lib64/libQtOpenGL.so.4+0x3b
#23  0x7f948a14df6e in CustomGLWidget::~CustomGLWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x40
#24  0x7f948a14df90 in CustomGLWidget::~CustomGLWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#25  0x7f948389a874 in QObjectPrivate::deleteChildren() from /lib64/libQtCore.so.4+0x84
#26  0x7f9483ea5d00 in QWidget::~QWidget() from /lib64/libQtGui.so.4+0x330
#27  0x7f948a14adef in SIM::Coin3D::Quarter::QuarterWidget::~QuarterWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x151
#28  0x7f948a15258d in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::~SoQTQuarterAdaptor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0xbb
#29  0x7f948a184ea6 in Gui::View3DInventorViewer::~View3DInventorViewer() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x48c
#30  0x7f948a184edc in Gui::View3DInventorViewer::~View3DInventorViewer() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#31  0x7f948a17be24 in Gui::View3DInventor::~View3DInventor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x1ae
#32  0x7f948a17be8e in Gui::View3DInventor::~View3DInventor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#33  0x7f948389a874 in QObjectPrivate::deleteChildren() from /lib64/libQtCore.so.4+0x84
#34  0x7f9483ea5d00 in QWidget::~QWidget() from /lib64/libQtGui.so.4+0x330
#35  0x7f9484278802 in QMdiSubWindow::~QMdiSubWindow() from /lib64/libQtGui.so.4+0x12
#36  0x7f948389b630 in QObject::event(QEvent*) from /lib64/libQtCore.so.4+0x210
#37  0x7f9483ea650a in QWidget::event(QEvent*) from /lib64/libQtGui.so.4+0x50a
#38  0x7f94842790c3 in QMdiSubWindow::event(QEvent*) from /lib64/libQtGui.so.4+0x143
#39  0x7f9483e516c0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x80
#40  0x7f9483e58122 in QApplication::notify(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x1a2
#41  0x7f9489e3442f in Gui::GUIApplication::notify(QObject*, QEvent*) from /svn/linkstage3_build/lib/libFreeCADGui.so+0xff
#42  0x7f948388236f in QCoreApplication::notifyInternal(QObject*, QEvent*) from /lib64/libQtCore.so.4+0x6f
#43  0x7f9483884f85 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib64/libQtCore.so.4+0x195
#44  0x7f9483886375 in QCoreApplication::exec() from /lib64/libQtCore.so.4+0xd5
#45  0x7f9489d4160d in Gui::Application::runApplication() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x22c9
#46  ./FreeCAD(main+0xa17) [0x409013]
#47  /lib64/libc.so.6(__libc_start_main+0xf3) [0x7f9483049413]
#48  ./FreeCAD(_start+0x2e) [0x4084ce]

```

I will try to narrow it down a bit and provide a fcstd.

OK , here is a renamed tar.gz : 

[SBR20-beam-crash-collection.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2664349/SBR20-beam-crash-collection.zip)

I open the top level file SBR20-on-beam.fcstd . Once it has finished fiddling around I do File | Close , one by one. When the last file is closed I still see File | Close All enabled , although File | Close is now greyed out. 

I think there is a bug in the way the number of tabs/files open is being counted. Maybe due to the dummy files "start page" and unrequested "unnamed" file. This relates to similar issues I flagged a few days ago. 

the other similar problems I've been hitting today may also relate to closing assy view in the main window and indexing going astray, leading to a crash when a later file is closed and an invalid pointer is used in closing. 

I'm guessing but it looks like a corrupted linked list problem.

This is a crash I got from that collection of files.

```

Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x385c0) [0x7f91cc4bf5c0]
#1  /usr/lib64/dri/nouveau_dri.so(+0x59f1b9) [0x7f91bf6e21b9]
#2  /usr/lib64/dri/nouveau_dri.so(+0x46ff4e) [0x7f91bf5b2f4e]
#3  /usr/lib64/dri/nouveau_dri.so(+0x2ade6a) [0x7f91bf3f0e6a]
#4  /usr/lib64/dri/nouveau_dri.so(+0x271186) [0x7f91bf3b4186]
#5  /usr/lib64/dri/nouveau_dri.so(+0x2c60fe) [0x7f91bf4090fe]
#6  /usr/lib64/dri/nouveau_dri.so(+0x1d8720) [0x7f91bf31b720]
#7  /usr/lib64/dri/nouveau_dri.so(+0x1d89e8) [0x7f91bf31b9e8]
#8  /usr/lib64/dri/nouveau_dri.so(+0x1d8a73) [0x7f91bf31ba73]
#9  /usr/lib64/dri/nouveau_dri.so(+0x1d8b8d) [0x7f91bf31bb8d]
#10  /usr/lib64/dri/nouveau_dri.so(+0x2c0ff9) [0x7f91bf403ff9]
#11  /usr/lib64/dri/nouveau_dri.so(+0x2c11c2) [0x7f91bf4041c2]
#12  /usr/lib64/dri/nouveau_dri.so(+0x2c6229) [0x7f91bf409229]
#13  /usr/lib64/dri/nouveau_dri.so(+0xbc3d8) [0x7f91bf1ff3d8]
#14  /usr/lib64/dri/nouveau_dri.so(+0x27b8fd) [0x7f91bf3be8fd]
#15  /usr/lib64/dri/nouveau_dri.so(+0x4638cd) [0x7f91bf5a68cd]
#16  /usr/lib64/dri/nouveau_dri.so(+0x4626d7) [0x7f91bf5a56d7]
#17  /lib64/libGLX_mesa.so.0(+0x49d03) [0x7f91bff93d03]
#18  /lib64/libGLX_mesa.so.0(+0x1d3b1) [0x7f91bff673b1]
#19  0x7f91d011a5a9 in QGLContext::reset() from /lib64/libQtOpenGL.so.4+0x89
#20  0x7f91d00a816c in QGLContext::~QGLContext() from /lib64/libQtOpenGL.so.4+0x5c
#21  0x7f91d00a81c2 in QGLContext::~QGLContext() from /lib64/libQtOpenGL.so.4+0x12
#22  0x7f91d00a1bab in QGLWidget::~QGLWidget() from /lib64/libQtOpenGL.so.4+0x3b
#23  0x7f91d35aff6e in CustomGLWidget::~CustomGLWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x40
#24  0x7f91d35aff90 in CustomGLWidget::~CustomGLWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#25  0x7f91cccfc874 in QObjectPrivate::deleteChildren() from /lib64/libQtCore.so.4+0x84
#26  0x7f91cd307d00 in QWidget::~QWidget() from /lib64/libQtGui.so.4+0x330
#27  0x7f91d35acdef in SIM::Coin3D::Quarter::QuarterWidget::~QuarterWidget() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x151
#28  0x7f91d35b458d in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::~SoQTQuarterAdaptor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0xbb
#29  0x7f91d35e6ea6 in Gui::View3DInventorViewer::~View3DInventorViewer() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x48c
#30  0x7f91d35e6edc in Gui::View3DInventorViewer::~View3DInventorViewer() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#31  0x7f91d35dde24 in Gui::View3DInventor::~View3DInventor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x1ae
#32  0x7f91d35dde8e in Gui::View3DInventor::~View3DInventor() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x18
#33  0x7f91cccfc874 in QObjectPrivate::deleteChildren() from /lib64/libQtCore.so.4+0x84
#34  0x7f91cd307d00 in QWidget::~QWidget() from /lib64/libQtGui.so.4+0x330
#35  0x7f91cd6da802 in QMdiSubWindow::~QMdiSubWindow() from /lib64/libQtGui.so.4+0x12
#36  0x7f91cccfd630 in QObject::event(QEvent*) from /lib64/libQtCore.so.4+0x210
#37  0x7f91cd30850a in QWidget::event(QEvent*) from /lib64/libQtGui.so.4+0x50a
#38  0x7f91cd6db0c3 in QMdiSubWindow::event(QEvent*) from /lib64/libQtGui.so.4+0x143
#39  0x7f91cd2b36c0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x80
#40  0x7f91cd2ba122 in QApplication::notify(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x1a2
#41  0x7f91d329642f in Gui::GUIApplication::notify(QObject*, QEvent*) from /svn/linkstage3_build/lib/libFreeCADGui.so+0xff
#42  0x7f91ccce436f in QCoreApplication::notifyInternal(QObject*, QEvent*) from /lib64/libQtCore.so.4+0x6f
#43  0x7f91ccce6f85 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib64/libQtCore.so.4+0x195
#44  /lib64/libQtCore.so.4(+0x1e842d) [0x7f91ccd1242d]
#45  /lib64/libglib-2.0.so.0(g_main_context_dispatch+0x15d) [0x7f91c996226d]
#46  /lib64/libglib-2.0.so.0(+0x4e638) [0x7f91c9962638]
#47  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7f91c99626d0]
#48  0x7f91ccd12589 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x79
#49  /lib64/libQtGui.so.4(+0x33b68b) [0x7f91cd35668b]
#50  0x7f91ccce2b23 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x43
#51  0x7f91ccce2dfe in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x11e
#52  0x7f91ccce833e in QCoreApplication::exec() from /lib64/libQtCore.so.4+0x9e
#53  0x7f91d31a360d in Gui::Application::runApplication() from /svn/linkstage3_build/lib/libFreeCADGui.so+0x22c9
#54  ./FreeCAD(main+0xa17) [0x409013]
#55  /lib64/libc.so.6(__libc_start_main+0xf3) [0x7f91cc4ab413]
#56  ./FreeCAD(_start+0x2e) [0x4084ce]

```

**Comment by luzpaz** [comment]
@realthunder verdict?

**Comment by luzpaz** [comment]
@realthunder can you recreate?

**Comment by realthunder** [comment]
No, I can't recreate it. Like the OP said, probably graphics driver related.

**Comment by luzpaz** [comment]
Thanks. Then closing ticket
