### ISSUE TITLE
Segmentation fault when deleting external geometry element

### ISSUE THREAD

**Issue by bgamari** [realthunder/FreeCAD_assembly3#199]
Attached is a design which causes FreeCAD 4664316 (the realthunder AppImage release) to crash on Linux.

To reproduce:

1. Open the design
2. Open `pump-bracket/Body/Pad002/Pump mount` in Sketcher
3. Scroll to the end of the "Elements" list in the sidebar
4. Select either `ExternalEdge1` or `ExternalEdge2`
5. Press the Delete key

FreeCAD will segmentation fault:
```
$ nix run -f .nix-overlay/ freecad-realthunder -c FreeCAD
FreeCAD 0.18, Libs: 0.18R16268 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2018
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##


<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch003.e4 missing reference: Pad001.;#11c;:G3#1c9;FUS;:T11:4:E
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch003.e6 missing reference: Pad001.;#169;:T17:4:E
Exception (Fri Mar  8 18:50:40 2019): Missing external geometry reference  
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch002.e7 missing reference: Mirrored.;#d0;:T-14:3:E
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch002.e8 missing reference: Mirrored.;#d4;:T-14:3:E
Exception (Fri Mar  8 18:50:40 2019): Missing external geometry reference  
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch003.e4 missing reference: Pad001.;#11c;:G3#1c9;FUS;:T11:4:E
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch003.e6 missing reference: Pad001.;#169;:T17:4:E
Exception (Fri Mar  8 18:50:40 2019): Missing external geometry reference  
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch002.e7 missing reference: Mirrored.;#d0;:T-14:3:E
<Sketcher> SketchObject.cpp(6503): External geometry pump_bracket#Sketch002.e8 missing reference: Mirrored.;#d4;:T-14:3:E
Exception (Fri Mar  8 18:50:40 2019): Missing external geometry reference  
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/libc.so.6(+0x34c20) [0x7f99199cec20]
#1  0x7f98a1f6e353 in SketcherGui::ViewProviderSketch::updateColor() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x7f3
#2  0x7f98a1f7235a in SketcherGui::ViewProviderSketch::onSelectionChanged(Gui::SelectionChanges const&) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x7da
#3  0x7f991cbeae5f in Gui::SelectionObserver::_onSelectionChanged(Gui::SelectionChanges const&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x1f
#4  0x7f991cc02fdc in boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x1fc
#5  0x7f991cbf0df6 in Gui::SelectionSingleton::slotSelectionChanged(Gui::SelectionChanges const&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x236
#6  0x7f991cc02fdc in boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x1fc
#7  0x7f991cbf2f50 in Gui::SelectionSingleton::notify(Gui::SelectionChanges&&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x100
#8  0x7f991cbf3ac1 in Gui::SelectionSingleton::setPreselect(char const*, char const*, char const*, float, float, float, int) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x2e1
#9  0x7f98a1f42c42 in SketcherGui::TaskSketcherElements::on_elementsWidget_itemEntered(QTreeWidgetItem*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x5f2
#10  0x7f991a47d87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x2da
#11  0x7f991af04310 in QTreeWidget::itemEntered(QTreeWidgetItem*, int) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x40
#12  0x7f991a47d87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x2da
#13  0x7f991ae92625 in QAbstractItemView::entered(QModelIndex const&) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x25
#14  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x6c96e3) [0x7f991ae9a6e3]
#15  0x7f991ae9af8f in QAbstractItemView::verticalScrollbarValueChanged(int) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0xcf
#16  0x7f991a47d87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x2da
#17  0x7f991afe956e in QAbstractSlider::valueChanged(int) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x2e
#18  0x7f991aed2022 in QTreeViewPrivate::updateScrollBars() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0xb2
#19  0x7f991aedb377 in QTreeView::updateGeometries() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x197
#20  0x7f991ae8e56d in QAbstractItemView::doItemsLayout() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x2d
#21  0x7f991aeda995 in QTreeView::doItemsLayout() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0xd5
#22  0x7f991aecd4a4 in QTreeView::resizeColumnToContents(int) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x34
#23  0x7f98a1f43ea5 in SketcherGui::TaskSketcherElements::slotElementsChanged() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x3e5
#24  0x7f98a1f90e52 in boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x1b2
#25  0x7f98a1f848d2 in SketcherGui::ViewProviderSketch::updateData(App::Property const*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x102
#26  0x7f991c88bc86 in Gui::Document::slotChangedObject(App::DocumentObject const&, App::Property const&) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x36
#27  0x7f991bf65703 in boost::signals2::detail::signal_impl<void (App::DocumentObject const&, App::Property const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (App::DocumentObject const&, App::Property const&)>, boost::function<void (boost::signals2::connection const&, App::DocumentObject const&, App::Property const&)>, boost::signals2::mutex>::operator()(App::DocumentObject const&, App::Property const&) from ././/lib/freecad-daily/lib/libFreeCADApp.so+0x1e3
#28  0x7f991bf740aa in App::DocumentObject::onChanged(App::Property const*) from ././/lib/freecad-daily/lib/libFreeCADApp.so+0x7a
#29  0x7f98fc73378c in Part::Feature::onChanged(App::Property const*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Part.so+0x3c
#30  0x7f98a2ec848e in Sketcher::SketchObject::onChanged(App::Property const*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Sketcher.so+0x6e
#31  0x7f991c074319 in App::Property::hasSetValue() from ././/lib/freecad-daily/lib/libFreeCADApp.so+0x19
#32  0x7f98fc75810d in Part::PropertyGeometryList::setValues(std::vector<Part::Geometry*, std::allocator<Part::Geometry*> >&&) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Part.so+0x24d
#33  0x7f98a2eafffa in Sketcher::SketchObject::delExternalPrivate(std::set<long, std::less<long>, std::allocator<long> > const&, bool) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Sketcher.so+0x5aa
#34  0x7f98a2ec05c7 in Sketcher::SketchObject::delExternal(int) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Sketcher.so+0xe7
#35  0x7f98a2f393ac in Sketcher::SketchObjectPy::delExternal(_object*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Sketcher.so+0x3c
#36  0x7f98a2f394a7 in Sketcher::SketchObjectPy::staticCallback_delExternal(_object*, _object*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/Sketcher.so+0x27
#37  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4bd4) [0x7f991b5e40d4]
#38  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d) [0x7f991b5e617d]
#39  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCode+0x32) [0x7f991b5e6462]
#40  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyRun_StringFlags+0x79) [0x7f991b52aac9]
#41  0x7f991ba97044 in Base::InterpreterSingleton::runString(char const*) from ././/lib/freecad-daily/lib/libFreeCADBase.so+0x54
#42  0x7f991c8de638 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x78
#43  0x7f991c8de7a3 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0xf3
#44  0x7f98a1f865f6 in SketcherGui::ViewProviderSketch::onDelete(std::vector<std::string, std::allocator<std::string> > const&) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/lib/SketcherGui.so+0x636
#45  0x7f991c8eb5cd in StdCmdDelete::activated(int) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x1ed
#46  0x7f991c8e3813 in Gui::Command::invoke(int, bool, Gui::Command::TriggerSource) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x163
#47  0x7f991a47d87a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x2da
#48  0x7f991a994a62 in QAction::triggered(bool) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x32
#49  0x7f991a996433 in QAction::activate(QAction::ActionEvent) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x63
#50  0x7f991a99658c in QAction::event(QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0xac
#51  0x7f991a99ae2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x8c
#52  0x7f991a9a14a0 in QApplication::notify(QObject*, QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x270
#53  0x7f991c8be2d1 in Gui::GUIApplication::notify(QObject*, QEvent*) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x41
#54  0x7f991a4694dd in QCoreApplication::notifyInternal(QObject*, QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x6d
#55  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x1fb2a6) [0x7f991a9cc2a6]
#56  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x1fb3dc) [0x7f991a9cc3dc]
#57  0x7f991a9a2773 in QApplication::notify(QObject*, QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x1543
#58  0x7f991c8be2d1 in Gui::GUIApplication::notify(QObject*, QEvent*) from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x41
#59  0x7f991a4694dd in QCoreApplication::notifyInternal(QObject*, QEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x6d
#60  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x268ff7) [0x7f991aa39ff7]
#61  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x269399) [0x7f991aa3a399]
#62  0x7f991aa143f7 in QApplication::x11ProcessEvent(_XEvent*) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x6e7
#63  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x26bb02) [0x7f991aa3cb02]
#64  /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x31f) [0x7f99133ddd6f]
#65  /usr/lib/libglib-2.0.so.0(+0x5e020) [0x7f99133de020]
#66  /usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f99133de1fc]
#67  0x7f991a4967a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x71
#68  /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x26bbb6) [0x7f991aa3cbb6]
#69  0x7f991a4680af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x2f
#70  0x7f991a4683a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x175
#71  0x7f991a46db79 in QCoreApplication::exec() from /home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x89
#72  0x7f991c84fd49 in Gui::Application::runApplication() from ././/lib/freecad-daily/lib/libFreeCADGui.so+0x1669
#73  freecad-daily(main+0x74b) [0x40355b]
#74  /usr/lib/libc.so.6(__libc_start_main+0xee) [0x7f99199bbb5e]
#75  freecad-daily() [0x4044c7]
```

**Comment by bgamari** [comment]
Design exhibiting crash. There does appear to be something wrong with the dependency graph of this design (if you have any ideas on this let me know; I'm rather stuck) but nevertheless it shouldn't crash.

[repro.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2947849/repro.zip)

**Comment by realthunder** [comment]
Thanks for the report. Bug confirmed. As a temporary workaround, just move your mouse away from the element list before hitting delete key.

**Comment by bgamari** [comment]
@realthunder, thank you!
