### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by bgamari** [realthunder/FreeCAD_assembly3#222]
Clicking on the "Solve constraints" button fails with a "List index out of range" exception in the attached model. I believe the problem is the `AxialAlignment001` constraint.

[lamp-mount-2.zip](https://github.com/realthunder/FreeCAD_assembly3/files/3055535/lamp-mount-2.zip)

```
FreeCAD
FreeCAD 0.18, Libs: 0.18R16268 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2018
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

11.102908 <asm3.cstr> constraint.py(1081): lamp_mount_2#Constraint008 skip more than one fixed part Link,Workplane001
0.000134 <asm3.cstr> constraint.py(1087): lamp_mount_2#Constraint008 has no effective constraint
11.10447 <asm3.gui> gui.py(282): command "asm3CmdSolve" exception
Traceback (most recent call last):
  File "<string>", line 595, in report
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/solver.py", line 404, in solve
    return _solve(*args,**kargs)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/solver.py", line 374, in _solve
    Solver(assembly,reportFailed,dragPart,recompute,rollback)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/solver.py", line 74, in __init__
    ret = Constraint.prepare(cstr,self)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/constraint.py", line 494, in prepare
    return mcs.getProxy(obj).prepare(obj,solver)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/constraint.py", line 1098, in prepare
    solver,partInfo,info.Subname,info.Shape)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/constraint.py", line 236, in _lna
    return _ln(solver,partInfo,subname,shape,True)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/constraint.py", line 231, in _ln
    return _l(solver,partInfo,subname,shape,retAll)
  File "/home/ben/.cache/appimage-run/da21b40d5cb5adf386e4a1a9eff26e0c78166bd2335e72731db16bc51497bba8/squashfs-root/usr/lib/freecad-daily/Ext/freecad/asm3/constraint.py", line 194, in _l
    p0 = system.addPoint3dV(*v[0].Point)
IndexError: list index out of range

```

**Comment by realthunder** [comment]
The problem is fixed. It is related to infinite line shape returned by the datum object. If you are not building my branch yourself, please wait for the next release. Should be soon.

BTW, there is some inconsistent constraints in your attached file. Specifically, `refPlane` and `_Element049` are both locked, but there is a `PlaneAlignment` on `refPlane` and `Arm2Plane` which has the same owner object as `_Element049`.
