### ISSUE TITLE
"Inconsistent constraints" error is not clear

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#225]
While creating a model there may be some errors, naturally. Clearance of the errors might not be that much important while building the model because we can easily guess that it is possibly because of our last action. 

However, if we replace a part with a different topology (delete two parts, replace it with a single bent part), the following error makes problems very confusing: 

```
1944.761705 <asm3.sys> solver.py(120): List of failed constraint:
sigle_driver#Constraint001, handle: 1
sigle_driver#Constraint001, handle: 2
sigle_driver#Constraint002, handle: 3
sigle_driver#Constraint002, handle: 4
sigle_driver#Constraint003, handle: 5
sigle_driver#Constraint004, handle: 6
sigle_driver#Constraint004, handle: 7
sigle_driver#Constraint005, handle: 8
sigle_driver#Constraint005, handle: 9
sigle_driver#Constraint009, handle: 10
sigle_driver#Constraint009, handle: 11
sigle_driver#Constraint010, handle: 12
sigle_driver#Constraint010, handle: 13
sigle_driver#Constraint011, handle: 14
sigle_driver#Constraint011, handle: 15
sigle_driver#Constraint012, handle: 16
sigle_driver#Constraint013, handle: 17
sigle_driver#Constraint013, handle: 18
sigle_driver#Constraint014, handle: 19
sigle_driver#Constraint014, handle: 20
sigle_driver#Constraint015, handle: 21
sigle_driver#Constraint015, handle: 22
sigle_driver#Constraint016, handle: 23
sigle_driver#Constraint016, handle: 24
sigle_driver#Constraint019, handle: 25
sigle_driver#Constraint019, handle: 26
sigle_driver#Constraint021, handle: 27
sigle_driver#Constraint021, handle: 28
sigle_driver#Constraint022, handle: 29
sigle_driver#Constraint022, handle: 30
sigle_driver#Constraint023, handle: 31
sigle_driver#Constraint024, handle: 32
sigle_driver#Constraint024, handle: 33
sigle_driver#Constraint026, handle: 34
sigle_driver#Constraint026, handle: 35
sigle_driver#Constraint027, handle: 36
sigle_driver#Constraint027, handle: 37
sigle_driver#Constraint028, handle: 38
sigle_driver#Constraint028, handle: 39
sigle_driver#Constraint029, handle: 40
sigle_driver#Constraint029, handle: 41
sigle_driver#Constraint030, handle: 42
sigle_driver#Constraint030, handle: 43
sigle_driver#Constraint031, handle: 44
sigle_driver#Constraint031, handle: 45
sigle_driver#Constraint032, handle: 46
sigle_driver#Constraint032, handle: 47
sigle_driver#Constraint033, handle: 48
sigle_driver#Constraint033, handle: 49
sigle_driver#Constraint036, handle: 50
sigle_driver#Constraint036, handle: 51
sigle_driver#Constraint037, handle: 52
sigle_driver#Constraint037, handle: 53
sigle_driver#Constraint038, handle: 54
sigle_driver#Constraint040, handle: 55
sigle_driver#Constraint040, handle: 56
sigle_driver#Constraint041, handle: 57
sigle_driver#Constraint041, handle: 58
sigle_driver#Constraint042, handle: 59
sigle_driver#Constraint042, handle: 60
sigle_driver#Constraint043, handle: 61
sigle_driver#Constraint043, handle: 62
sigle_driver#Constraint044, handle: 63
sigle_driver#Constraint045, handle: 64
sigle_driver#Constraint046, handle: 65
sigle_driver#Constraint047, handle: 66
sigle_driver#Constraint048, handle: 67
sigle_driver#Constraint049, handle: 68
sigle_driver#Constraint050, handle: 69
sigle_driver#Constraint051, handle: 70
sigle_driver#Constraint052, handle: 71
sigle_driver#Constraint052, handle: 72
sigle_driver#Constraint053, handle: 73
sigle_driver#Constraint053, handle: 74
sigle_driver#Constraint054, handle: 75
sigle_driver#Constraint054, handle: 76
sigle_driver#Constraint055, handle: 77
sigle_driver#Constraint055, handle: 78
sigle_driver#Constraint056, handle: 79
sigle_driver#Constraint056, handle: 80
sigle_driver#Constraint057, handle: 81
sigle_driver#Constraint057, handle: 82
sigle_driver#Constraint058, handle: 83
sigle_driver#Constraint058, handle: 84
sigle_driver#Constraint059, handle: 85
sigle_driver#Constraint059, handle: 86
sigle_driver#Constraint060, handle: 87
sigle_driver#Constraint060, handle: 88
sigle_driver#Constraint061, handle: 89
sigle_driver#Constraint061, handle: 90
sigle_driver#Constraint062, handle: 91
sigle_driver#Constraint063, handle: 92
sigle_driver#Constraint064, handle: 93
sigle_driver#Constraint065, handle: 94
sigle_driver#Constraint066, handle: 95
sigle_driver#Constraint067, handle: 96
sigle_driver#Constraint068, handle: 97
sigle_driver#Constraint069, handle: 98
sigle_driver#Constraint070, handle: 99
sigle_driver#Constraint070, handle: 100
sigle_driver#Constraint071, handle: 101
sigle_driver#Constraint072, handle: 102
sigle_driver#Constraint072, handle: 103
sigle_driver#Constraint073, handle: 104
sigle_driver#Constraint074, handle: 105
sigle_driver#Constraint074, handle: 106
sigle_driver#Constraint075, handle: 107
sigle_driver#Constraint076, handle: 108
sigle_driver#Constraint076, handle: 109
sigle_driver#Constraint076, handle: 110
sigle_driver#Constraint077, handle: 111
sigle_driver#Constraint079, handle: 112
sigle_driver#Constraint079, handle: 113
sigle_driver#Constraint080, handle: 114
sigle_driver#Constraint080, handle: 115
sigle_driver#Constraint081, handle: 116
sigle_driver#Constraint082, handle: 117
sigle_driver#Constraint082, handle: 118
sigle_driver#Constraint083, handle: 119
sigle_driver#Constraint084, handle: 120
sigle_driver#Constraint084, handle: 121
sigle_driver#Constraint085, handle: 122
sigle_driver#Constraint085, handle: 123
sigle_driver#Constraint086, handle: 124
sigle_driver#Constraint086, handle: 125
sigle_driver#Constraint087, handle: 126
sigle_driver#Constraint087, handle: 127
sigle_driver#Constraint088, handle: 128
sigle_driver#Constraint088, handle: 129
sigle_driver#Constraint089, handle: 130
sigle_driver#Constraint089, handle: 131
sigle_driver#Constraint090, handle: 132
sigle_driver#Constraint090, handle: 133
sigle_driver#Constraint091, handle: 134
sigle_driver#Constraint093, handle: 135
sigle_driver#Constraint094, handle: 136
sigle_driver#Constraint095, handle: 137
sigle_driver#Constraint095, handle: 138
sigle_driver#Constraint096, handle: 139
sigle_driver#Constraint096, handle: 140
sigle_driver#Constraint097, handle: 141
sigle_driver#Constraint098, handle: 142
sigle_driver#Constraint098, handle: 143
sigle_driver#Constraint099, handle: 144
sigle_driver#Constraint099, handle: 145
sigle_driver#Constraint100, handle: 146
sigle_driver#Constraint103, handle: 147
sigle_driver#Constraint103, handle: 148
sigle_driver#Constraint104, handle: 149
sigle_driver#Constraint104, handle: 150
sigle_driver#Constraint105, handle: 151
sigle_driver#Constraint105, handle: 152
sigle_driver#Constraint106, handle: 153
sigle_driver#Constraint107, handle: 154
sigle_driver#Constraint108, handle: 155
sigle_driver#Constraint109, handle: 156
sigle_driver#Constraint110, handle: 157
sigle_driver#Constraint110, handle: 158
sigle_driver#Constraint111, handle: 159
sigle_driver#Constraint112, handle: 160
sigle_driver#Constraint112, handle: 161
sigle_driver#Constraint113, handle: 162
sigle_driver#Constraint114, handle: 163
sigle_driver#Constraint114, handle: 164
sigle_driver#Constraint115, handle: 165
sigle_driver#Constraint116, handle: 166
sigle_driver#Constraint118, handle: 167
sigle_driver#Constraint120, handle: 168
461.258637 <asm3.gui> gui.py(304): command "asm3CmdSolve" exception
Traceback (most recent call last):
  File "<string>", line 595, in report
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 404, in solve
    return _solve(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 374, in _solve
    Solver(assembly,reportFailed,dragPart,recompute,rollback)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 101, in __init__
    objName(assembly),str(e)))
RuntimeError: Failed to solve sigle_driver#Assembly: inconsistent constraints
```

There is no exclamation mark or any other clue in the tree and "Inconsistent constraints" are not sufficient to understand the underlying problem. 

# Expectation 

When there are inconsistent constraints, the constraints should contain an exclamation mark.

**Comment by ceremcem** [comment]
Currently all backups are getting broken with the same exception after they are recomputed. 

# Version 

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16526 (Git)
Build type: Release
Branch: LinkStage3
Hash: 978992c9a889298431fbe4f947cf63f1c1798a5e
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by ceremcem** [comment]
Probably this error is related with #229

**Comment by ceremcem** [comment]
I can confirm that the "Inconsistent constraints" error is related with #229 and is vanished after the fix. This means that "Inconsistent constraints" error is a type of error that is thrown only because of after our last action. If that's the case, this issue should be closed.
