### ISSUE TITLE
Lingering data structures after decreasing Element Count

### ISSUE THREAD

**Issue by mdjurfeldt** [realthunder/FreeCAD_assembly3#277]
* When I decreased object count for a component Assembly from 6 to 4, constraints on and elements of the removed 2 links still lingered in the object tree. Shouldn't these be automatically removed?

* When I manually removed all surplus objects from the tree, the solver still complains about the removed objects:

Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
8e-08 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element013: 'tuple' object has no attribute 'Name'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
0.00786397 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element015: 'tuple' object has no attribute 'Name'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
0.0100167 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element016: 'tuple' object has no attribute 'Name'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
0.0115722 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element017: 'tuple' object has no attribute 'Name'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
0.0127241 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element018: 'tuple' object has no attribute 'Name'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 608, in execute
    self.updatePlacement()
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 663, in updatePlacement
    self.getElementSubname(),False,True)
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1291, in getElementInfo
    part.Name,names[1])
<type 'exceptions.AttributeError'>: 'tuple' object has no attribute 'Name'
0.0137694 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#_Element019: 'tuple' object has no attribute 'Name'
Recompute failed! Please check report view.
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5613 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink013: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5623 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink015: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5634 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink016: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5643 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink017: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5651 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink018: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
34.5658 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink019: 'NoneType' object has no attribute 'getSubObject'
Recompute failed! Please check report view.
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
47.8075 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink013: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
47.808 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink015: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
47.8084 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink016: 'NoneType' object has no attribute 'getSubObject'
Traceback (most recent call last):
  File "/home/mdj/.FreeCAD/Mod/asm3/freecad/asm3/assembly.py", line 1446, in execute
    linked,mat = link.getSubObject(subname,1,FreeCAD.Matrix())
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getSubObject'
47.8087 <App> Document.cpp(3462): Failed to recompute spice_shelf_6_whole#ElementLink017: 'NoneType' object has no attribute 'getSubObject'
Recompute failed! Please check report view.

**Comment by realthunder** [comment]
Yes, I probably should make it more user friendly and ask the user if he/she wants to delete the constraint together. For now, you'll have to manually delete them. Maybe you can send me the file to find out what are those lingering objects
