### ISSUE TITLE
Error when 'Freeze' an assembly

### ISSUE THREAD

**Issue by lilaL** [realthunder/FreeCAD_assembly3#286]
The following error appears when trying to freeze an assembly:
```
Traceback (most recent call last):
  File "/tmp/.mount_FreeCA3T1nbL/usr/Mod/asm3/freecad/asm3/assembly.py", line 4356, in updateData
    self.showParts()
  File "/tmp/.mount_FreeCA3T1nbL/usr/Mod/asm3/freecad/asm3/assembly.py", line 4350, in showParts
    proxy.getPartGroup().ViewObject.Proxy.showParts()
  File "/tmp/.mount_FreeCA3T1nbL/usr/Mod/asm3/freecad/asm3/assembly.py", line 426, in showParts
    if not assembly.ViewObject.ShowParts and \
<class 'AttributeError'>: 'Gui.ViewProviderLink' object has no attribute 'ShowParts'
```
Using 0.11 2020.05.04

**Comment by lilaL** [comment]
🤩
