### ISSUE TITLE
Error when creating an element

### ISSUE THREAD

**Issue by lilaL** [realthunder/FreeCAD_assembly3#342]
Sometimes when I want to add an element to a part of an unfreezed assembly, I get the following message:

```
2210.423555 <asm3.gui> gui.py(330): Failed to add element
Traceback (most recent call last):
  File "<string>", line 611, in report
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 934, in make
    sel,name,False,radius,allowDuplicate))
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 1006, in make
    'element {}.{}'.format(objName(group),subname))
RuntimeError: Element must reference a geometry element Components_WindVane#Parts006.Edge3
```
In the treeview the part is also not selected:

![image](https://user-images.githubusercontent.com/12436228/99158618-e7465300-26d4-11eb-8051-fba4f9c5b405.png)

When I freeze the assembly, mysteriously i can select a geometry of a part. But yeah, it's frozen so I get the following message:
```
11.006499 <asm3.gui> gui.py(330): Failed to add element
Traceback (most recent call last):
  File "<string>", line 611, in report
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 926, in make
    ret = [AsmElement.make(sels[0],name,undo,radius,allowDuplicate)]
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 1063, in make
    element = AsmElement.create(name,elements)
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 913, in create
    raise RuntimeError('Cannot create new element in frozen assembly')
RuntimeError: Cannot create new element in frozen assembly
```
Once I restart it's working again ;) so no example file for now.

**Comment by lilaL** [comment]
I would close the issue for now as it seems to work fine!
