### ISSUE TITLE
Crash on cancelling creation of subtractive or additive features in Part Design

### ISSUE THREAD

**Issue by VorpalBlade** [realthunder/FreeCAD_assembly3#378]
First: I hope I put this bug in the right project (should it be realthunder/FreeCAD_assembly3 where the downloads are, or should it be realthunder/FreeCAD where the code in question is?).

To reproduce this crash:
1. Create a sketch in part design. Optionally add some 2D geometry (it doesn't matter for the bug).
2. Start an additive or subtractive feature (such as pad, pocket, loft etc).
3. Click cancel in the task view.

FreeCAD crashes.  Note, this happens even if there is a body to do a subtractive loft from, etc. I tested that this also happens with a clean `~/.FreeCAD` directory. Furthermore, it doesn't happen in the latest 0.19 as of writing this (0.19.23258 (Git) AppImage). 

I have seen a few different stack traces reported:
```
$ ./FreeCAD-asm3.AppImage
/tmp/.mount_FreeCArUsV3Z
FreeCAD 0.19, Libs: 2020.12.08R23076 +2912 (Git)
Loading Assembly4 WorkBench
Recompute failed! Please check report view.
Recompute failed! Please check report view.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f9ea9d38040]
#1  [0x56117295acf0]
```
and:
```
$ ./FreeCAD-asm3.AppImage
/tmp/.mount_FreeCAxxnf5N
FreeCAD 0.19, Libs: 2020.12.08R23076 +2912 (Git)
Loading Assembly4 WorkBench
Recompute failed! Please check report view.
Recompute failed! Please check report view.
/tmp/.mount_FreeCAxxnf5N/AppRun: line 32: 18458 Illegal instruction     (core dumped) ./"$name"Link "$@"
```
and:
```
Recompute failed! Please check report view.
Recompute failed! Please check report view.
Recompute failed! Please check report view.
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f8a05f1f040]
#1  0x7f8a07661089 in App::TransactionObject::applyChn(App::Document&, App::TransactionalObject*, bool) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADApp.so+0xe9
#2  0x7f8a07660d83 in App::Transaction::apply(App::Document&, bool) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADApp.so+0x103
#3  0x7f8a075560bb in App::Document::_abortTransaction() from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADApp.so+0x1cb
#4  0x7f8a07793dcf in App::Application::closeActiveTransaction(bool, int) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADApp.so+0x5af
#5  0x7f894155672d in PartDesignGui::TaskDlgFeatureParameters::reject() from /tmp/.mount_FreeCAn486aj/usr/lib64/PartDesignGui.so+0xad
#6  0x7f8a084baf8c in Gui::TaskView::TaskView::reject() from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADGui.so+0x5c
#7  0x7f8a064f10d2 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x780
#8  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5(+0x274d7d) [0x7f8a06e05d7d]
#9  0x7f8a064f10d2 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x780
#10  0x7f8a06d9e360 in QAbstractButton::clicked(bool) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x32
#11  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5(+0x20da19) [0x7f8a06d9ea19]
#12  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5(+0x20e2ae) [0x7f8a06d9f2ae]
#13  0x7f8a06d9f34a in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x88
#14  0x7f8a06d30c23 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x135
#15  0x7f8a06d0583a in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0xde
#16  0x7f8a06d0a0a9 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x79d
#17  0x7f8a081aa309 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADGui.so+0x89
#18  0x7f8a064daa9c in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x88
#19  0x7f8a06d09553 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x283
#20  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5(+0x1af580) [0x7f8a06d40580]
#21  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5(+0x1b03d2) [0x7f8a06d413d2]
#22  0x7f8a06d0583a in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0xde
#23  0x7f8a06d0b405 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Widgets.so.5+0x1af9
#24  0x7f8a081aa309 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADGui.so+0x89
#25  0x7f8a064daa9c in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x88
#26  0x7f8a06881724 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Gui.so.5+0x684
#27  0x7f8a068822f7 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Gui.so.5+0x175
#28  0x7f8a0686f020 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Gui.so.5+0x64
#29  /tmp/.mount_FreeCAn486aj/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5b1ea) [0x7f89fbf6b1ea]
#30  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x2cb) [0x7f8a01f3bdeb]
#31  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/./libglib-2.0.so.0(+0x55031) [0x7f8a01f3c031]
#32  /tmp/.mount_FreeCAn486aj/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f8a01f3c0be]
#33  0x7f8a06509d23 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x63
#34  0x7f8a064d74d7 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x187
#35  0x7f8a064db34f in QCoreApplication::exec() from /tmp/.mount_FreeCAn486aj/usr/bin/../lib/libQt5Core.so.5+0x105
#36  0x7f8a08125354 in Gui::Application::runApplication() from /tmp/.mount_FreeCAn486aj/usr/bin/../lib64/libFreeCADGui.so+0x1794
#37  ./FreeCADLink(+0x446f) [0x55f01a9a846f]
#38  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f8a05f01bf7]
#39  ./FreeCADLink(+0x4789) [0x55f01a9a8789]
```

FreeCAD version info:
```
OS: Ubuntu 18.04.5 LTS (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.12.08.23076 +2912 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 1eba27283118bae43f5264d38caf7451b848f49a
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)
```

**Comment by realthunder** [comment]
Thanks for the detailed report. You can report to either repo. Here is fine. This but has already been fixed (see #376). I'll make a new release soon.
