### ISSUE TITLE
Exporting the sphere to format Wavefront OBJ - Arch module *.obj fails

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#384]
Dear Realthunder,

While testing export to both obj formats, I found that exporting the sphere to format Wavefront OBJ - Arch module *.obj fails:
![obrázok](https://user-images.githubusercontent.com/74265320/102687480-a966ae00-41ef-11eb-917a-5c5a882b3417.png)
I checked this also in Win64 build from 2020-11-12 with the same result.

Report view:
11:48:28  Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "D:\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20201217\Mod\Arch\importOBJ.py", line 193, in exportSelection
    _export(objset, filename, colors)
  File "D:\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20201217\Mod\Arch\importOBJ.py", line 356, in _export
    vlist,vnlist,elist,flist,segments = getIndices(shape,offsetv,offsetvn,colorlist)
  File "D:\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20201217\Mod\Arch\importOBJ.py", line 78, in getIndices
    if isinstance(e.Curve,Part.LineSegment):
<class 'TypeError'>: undefined curve type

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.12.17.23076 +3024 (Git)
Build type: Release
Branch: LinkStage3
Hash: 560eb2c4645cd548b6f718c645c7af70384ff54c
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.4.0.beta
Locale: Slovak/Slovakia (sk_SK)

Best regards

**Comment by Rabbit-sk** [comment]
In comparison with the official branch, there is only warning in the Report view:
`Found a shape containing curves, triangulating`
and the outcome is less detailed as export to Alias Mesh obj, but it don't fail:
![obrázok](https://user-images.githubusercontent.com/74265320/102687642-cbacfb80-41f0-11eb-88e2-83efeda0acc4.png)

**Comment by Rabbit-sk** [comment]
It is fixed in version 2020.12.29.
