### ISSUE TITLE
Crashing when picking external geometry

### ISSUE THREAD

**Issue by LorenzoCerda** [realthunder/FreeCAD_assembly3#434]
Hi,

  First, thanks for such a nice work! Going to the issue:

 Using this file (attached) and selecting Sketch002. When using "Sketcher external geometry actions" and the selecting the left vertical side of the inner rectangle it crashes. This is using the last version (20210126). If I used the previous one (20201230) it doesn't crash, but I get a bunch of error (I think) in the Report View (copied and the end of this post).

  Thank you in advance!

[ESP-Ticket_v1.0c.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5889671/ESP-Ticket_v1.0c.zip)

### Traceback
```
FreeCAD 0.19, Libs: 2021.0126R23662 +3142 (Git)
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f1642035040]
#1  0x7f15652082d8 in Sketcher::SketchObject::rebuildExternalGeometry(bool) from /tmp/.mount_FreeCAppGBUB/usr/lib64/Sketcher.so+0x1f38
#2  0x7f156520d008 in Sketcher::SketchObject::addExternal(App::DocumentObject*, char const*, bool) from /tmp/.mount_FreeCAppGBUB/usr/lib64/Sketcher.so+0x3f8
#3  0x7f1565299c32 in Sketcher::SketchObjectPy::addExternal(_object*) from /tmp/.mount_FreeCAppGBUB/usr/lib64/Sketcher.so+0xe2
#4  0x7f156529a717 in Sketcher::SketchObjectPy::staticCallback_addExternal(_object*, _object*) from /tmp/.mount_FreeCAppGBUB/usr/lib64/Sketcher.so+0x57
#5  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(PyCFunction_Call+0xf2) [0x7f1643b45dc2]
#6  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(_PyObject_MakeTpCall+0x230) [0x7f1643aee080]
#7  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalFrameDefault+0x4ddd) [0x7f1643b579ed]
#8  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(_PyEval_EvalCodeWithName+0x2ea) [0x7f1643aef8ba]
#9  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f1643b7cb2a]
#10  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(PyEval_EvalCode+0x1c) [0x7f1643b7cb4c]
#11  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(+0x1dfbfa) [0x7f1643ba1bfa]
#12  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(+0x2238b5) [0x7f1643be58b5]
#13  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libpython3.8.so.1.0(PyRun_StringFlags+0x80) [0x7f1643be5950]
#14  0x7f164328db7c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADBase.so+0x6c
#15  0x7f164427cbc1 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x91
#16  0x7f164427cd61 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x101
#17  0x7f15645b419a in void Gui::cmdAppObjectArgs<char const* const&, char const* const&, char const*>(App::DocumentObject const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const* const&, char const* const&, char const*&&) from /tmp/.mount_FreeCAppGBUB/usr/lib64/SketcherGui.so+0x38a
#18  /tmp/.mount_FreeCAppGBUB/usr/lib64/SketcherGui.so(+0xf37ff) [0x7f15645c57ff]
#19  0x7f15646835a5 in SketcherGui::ViewProviderSketch::onSelectionChanged(Gui::SelectionChanges const&) from /tmp/.mount_FreeCAppGBUB/usr/lib64/SketcherGui.so+0x4b5
#20  0x7f164471f522 in Gui::SelectionObserver::_onSelectionChanged(Gui::SelectionChanges const&) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0xf2
#21  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so(+0x6ff90f) [0x7f164443390f]
#22  0x7f164471f793 in Gui::SelectionSingleton::slotSelectionChanged(Gui::SelectionChanges const&) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x253
#23  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so(+0x6ff90f) [0x7f164443390f]
#24  0x7f164472054e in Gui::SelectionSingleton::notify(Gui::SelectionChanges&&) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x1ee
#25  0x7f16447297d2 in Gui::SelectionSingleton::addSelection(char const*, char const*, char const*, float, float, float, std::vector<Gui::SelectionSingleton::SelObj, std::allocator<Gui::SelectionSingleton::SelObj> > const*, bool) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0xa62
#26  0x7f16444dd5d2 in Gui::SoFCUnifiedSelection::setSelection(std::vector<Gui::SoFCUnifiedSelection::PickedInfo, std::allocator<Gui::SoFCUnifiedSelection::PickedInfo> > const&, bool, bool, bool) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x10a2
#27  0x7f16444e1a28 in Gui::SoFCUnifiedSelection::handleEvent(SoHandleEventAction*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x348
#28  0x7f16419d41e9 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x69
#29  0x7f1641b94fea in SoChildList::traverse(SoAction*, int, int) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x16a
#30  0x7f1641be2b9a in SoGroup::doAction(SoAction*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x5a
#31  0x7f1641bfe1ab in SoSeparator::doAction(SoAction*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x2b
#32  0x7f16419d41e9 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x69
#33  0x7f16419ddf0c in SoHandleEventAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0xac
#34  0x7f16419d4eca in SoAction::apply(SoNode*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x2ea
#35  0x7f1641bae042 in SoEventManager::actuallyProcessEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/../lib/libCoin.so.80+0x72
#36  0x7f164456c19e in SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x1e
#37  0x7f164457441b in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x5b
#38  0x7f16445b522a in Gui::View3DInventorViewer::processSoEventBase(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0xa
#39  0x7f164457d7b7 in Gui::NavigationStyle::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x17
#40  0x7f164458363c in Gui::CADNavigationStyle::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x32c
#41  0x7f1644580090 in Gui::NavigationStyle::processEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x1a0
#42  0x7f16445ba2fa in Gui::View3DInventorViewer::processSoEvent(SoEvent const*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x8a
#43  0x7f16445649f1 in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0xd1
#44  0x7f1642592019 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0xcd
#45  0x7f1642dba7e1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5+0xcb
#46  0x7f1642dbef5e in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5+0x70a
#47  0x7f16442348c9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x89
#48  0x7f1642594606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0x86
#49  0x7f1642dbe4c4 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5+0x286
#50  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5(+0x1aefd4) [0x7f1642df4fd4]
#51  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5(+0x1aff7c) [0x7f1642df5f7c]
#52  0x7f1642dba7f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#53  0x7f1642dc031d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#54  0x7f16442348c9 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x89
#55  0x7f1642594606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0x86
#56  0x7f1642938ec5 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Gui.so.5+0x677
#57  0x7f164293991f in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Gui.so.5+0x5f
#58  0x7f1642926c65 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Gui.so.5+0x63
#59  /tmp/.mount_FreeCAppGBUB/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5b010) [0x7f1638218010]
#60  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f163dfc980d]
#61  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/./libglib-2.0.so.0(+0x54aa1) [0x7f163dfc9aa1]
#62  /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f163dfc9b41]
#63  0x7f16425c30e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0x5e
#64  0x7f1642591019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0x187
#65  0x7f1642594e8f in QCoreApplication::exec() from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib/libQt5Core.so.5+0xfd
#66  0x7f16441af5f7 in Gui::Application::runApplication() from /tmp/.mount_FreeCAppGBUB/usr/bin/../lib64/libFreeCADGui.so+0x1807
#67  /tmp/.mount_FreeCAppGBUB/usr/bin/FreeCADLink(+0x44bf) [0x55912d5244bf]
#68  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f1642017bf7]
#69  /tmp/.mount_FreeCAppGBUB/usr/bin/FreeCADLink(+0x47d9) [0x55912d5247d9]
```

### Version
OS: Ubuntu 18.04.5 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0126.23662 +3142 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 9732f5f35d54bd1546daaffc9c9cff7e2f0e0249
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

### View Report using version 20201230

```
17:00:30  XML Attribute: 'Ref' not found
In context: |ESP_Ticket_v1_0c|Sketch|ExternalGeo
17:00:30  XML Attribute: 'Ref' not found
In context: |ESP_Ticket_v1_0c|Sketch001|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch002|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch003|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch004|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch005|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch006|ExternalGeo
17:00:30  XML Attribute: 'Flags' not found
In context: |ESP_Ticket_v1_0c|Sketch007|ExternalGeo
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
17:00:30  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
```

**Comment by ceremcem** [comment]
@LorenzoCerda Is this issue solved?

**Comment by luzpaz** [comment]
I edited OPs post to put the code and log output in code tags as they were keyword-triggering other tickets.

**Comment by LorenzoCerda** [comment]
> @LorenzoCerda Is this issue solved?

Hi @ceremcem,

   Unfortunatelly I can't tell right now. At the moment I had to finish the model, so after failing in doing so with Asembly3, I switched back to the "official" FreeCad version (the one in the main fork, sort to speak) and I could do it there without problem. 

   Let me know if you need anything form my side and I could check. 

   Thanks again!

**Comment by ceremcem** [comment]
There was a release that includes the fix related to your issue: https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11. You may want to check if the issue persists or resolved.

**Comment by LorenzoCerda** [comment]
> There was a release that includes the fix related to your issue: https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11. You may want to check if the issue persists or resolved.

Sure. Give me some days and I will check it and let you know. 

Cheers

**Comment by oficinerobotica** [comment]
Tested the example file with: 
```
OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```
and the issue isn't present anymore.
