### ISSUE TITLE
Path workbench error while creating operations

### ISSUE THREAD

**Issue by Anducalliew** [realthunder/FreeCAD_assembly3#533]
Hi, I'm using the 20210311 version AppImage.
I have a problem with Path workbench and I'm not able to create any operation.

When I try to create a new operation I get this error:
```
Running the Python command 'Path_MillFace' failed:
Traceback (most recent call last):
  File "/tmp/XXXXXXXXXXXXXXXXXXX/usr/Mod/Path/PathScripts/PathOpGui.py", line 1319, in Activated
    return Create(self.res)
  File "/tmp/XXXXXXXXXXXXXXXXXXX/usr/Mod/Path/PathScripts/PathOpGui.py", line 1283, in Create
    obj = res.objFactory(res.name)
  File "/tmp/XXXXXXXXXXXXXXXXXXX/usr/Mod/Path/PathScripts/PathMillFace.py", line 311, in Create
    obj.Proxy = ObjectFace(obj, name)
  File "/tmp/XXXXXXXXXXXXXXXXXXX/usr/Mod/Path/PathScripts/PathOp.py", line 193, in __init__
    job = self.setDefaultValues(obj)
  File "/tmp/XXXXXXXXXXXXXXXXXXX/usr/Mod/Path/PathScripts/PathOp.py", line 338, in setDefaultValues
    obj.OpToolDiameter = obj.ToolController.Tool.Diameter

'FeaturePython' object has no attribute 'Diameter'
```

I tried with standard freecad version and it works.

**Comment by Anducalliew** [comment]
Fixed and reported here #524 and here #536
