### ISSUE TITLE
Running the Python command 'Path_Sanity' failed

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#663]
Got the path sanity working on official Freecad 0.19 and 0.20. Trying linkstage3 does not work. And after saving the file in Linkstage3 I get these errors in 0.19-0.20 and Linkstage3 itself.
https://wiki.freecadweb.org/Path_Sanity

( the experimental features was not enabled, after following https://wiki.freecadweb.org/Path_experimental it showed up and kinda works.)

`10:56:26  Running the Python command 'Path_Sanity' failed:
Traceback (most recent call last):
  File "C:\Users\woo_\Downloads\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20210528-2\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20210528\Mod\Path\PathScripts\PathSanity.py", line 119, in Activated
    html = self.__report(data)
  File "C:\Users\woo_\Downloads\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20210528-2\FreeCAD-asm3-Daily-Win64-Py3-Qt5-20210528\Mod\Path\PathScripts\PathSanity.py", line 304, in __report
    toolTables += "|*{}*| {} a| image::{}[{}]\n".format(descriptionLabel, value['description'], value['imagepath'], key)

('imagepath',)`

> OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.528.24301 +3686 (Git)
Build type: Release
Branch: LinkDaily
Hash: d69f4add39382592e7b4eefbe5091953cda727b6
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Dutch/Netherlands (nl_NL)

**Comment by snelweg** [comment]
Looks like I did something wrong, got it working now. After adding feeds and speeds it all started to work (kinda)
