### ISSUE TITLE
Often crashes on clicking "Save"

### ISSUE THREAD

**Issue by StudioPetrikas** [realthunder/FreeCAD_assembly3#668]
Hi,
Having some real issues when saving files. It happens often enough for me to be afraid to click save, but not enough that I can reproduce consistently. It feels like it crashes more frequently when I'm messing around sketches, surfaces (Curves WB) and splines.

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git)
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United Kingdom (en_GB)

Attaching the crash log, maybe there's something I can't figure out.
[crash.log](https://github.com/realthunder/FreeCAD_assembly3/files/6644322/crash.log)

Thank you in advance, loving and enjoying FreeCAD Link!

**Comment by realthunder** [comment]
How did you get the crash log? Did you run it under Visual Studio? It would be better if you can capture the call stack while crash, instead of just the linked DLLs as your attachment.

**Comment by StudioPetrikas** [comment]
> How did you get the crash log? Did you run it under Visual Studio?

The crashlog along with a crash dump file was generated in the users/freecad folder. I don't run FreeCAD with VS but I definitely need to learn how to - I will do that and return with the call stack. 
Thanks!

**Comment by StudioPetrikas** [comment]
I remember I had an error pop up, something relating to "illegal storage access" or similar. I moved FreeCAD folder out of Program Files today, just to see whether it could be a weird Windows Administration problem. And it seems to have fixed the issue.

Sorry for raising an issue.

**Comment by realthunder** [comment]
The `illegal storage access` indicates some serious unhandled exception somewhere in the code. I am not sure whether it is related to Admin problem.

**Comment by StudioPetrikas** [comment]
It may have been unrelated, since most of the save-crashes were completely without error. 
Haven't crashed in 2 days now, where before it was every 2-3 saves. Thanks again.

**Comment by oficinerobotica** [comment]
I experienced the SaveFile crash several times but it is not easy to find a clear pattern of when or why it happens. For this particular trace I'm not sure how to replicate the problem if needed. 

```
595.538975 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.670575 <asm3.sys> sys_slvs.py(68): dof remaining: 3
10.976821 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.484784 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.490162 <asm3.sys> sys_slvs.py(68): dof remaining: 3
1.755173 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.481616 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.491072 <asm3.sys> sys_slvs.py(68): dof remaining: 3
1.14444 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.478066 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.480584 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.709973 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.213541 <asm3.sys> sys_slvs.py(68): dof remaining: 3
0.260888 <asm3.sys> sys_slvs.py(68): dof remaining: 3
145.758292 <asm3.sys> sys_slvs.py(68): dof remaining: 0
13.931184 <asm3.sys> sys_slvs.py(68): dof remaining: 0
892.429175 <asm3.main> assembly.py(1128): _Element012 linked path [<App::Link object>, <PartDesign::Chamfer>]
0.052407 <asm3.main> assembly.py(1128): _Element013 linked path [<App::Link object>, <App::LinkElement object>]
118.816331 <asm3.sys> sys_slvs.py(68): dof remaining: 0
20.500543 <asm3.main> assembly.py(1128): _Element014 linked path [<App::Link object>, <PartDesign::Chamfer>]
0.053154 <asm3.main> assembly.py(1128): _Element015 linked path [<App::Link object>, <App::LinkElement object>]
20.572487 <asm3.sys> sys_slvs.py(68): dof remaining: 0
21.406435 <asm3.main> assembly.py(1128): _Element016 linked path [<App::Link object>, <PartDesign::Chamfer>]
0.055148 <asm3.main> assembly.py(1128): _Element017 linked path [<App::Link object>, <App::LinkElement object>]
21.593894 <asm3.sys> sys_slvs.py(68): dof remaining: 0
19.970225 <asm3.main> assembly.py(1128): _Element018 linked path [<App::Link object>, <PartDesign::Chamfer>]
0.056757 <asm3.main> assembly.py(1128): _Element019 linked path [<App::Link object>, <App::LinkElement object>]
20.665101 <asm3.sys> sys_slvs.py(68): dof remaining: 0
20.46494 <asm3.sys> sys_slvs.py(68): dof remaining: 0
7.097671 <asm3.sys> sys_slvs.py(68): dof remaining: 0
7.907616 <asm3.sys> sys_slvs.py(68): dof remaining: 0
6.842296 <asm3.sys> sys_slvs.py(68): dof remaining: 0
17.425068 <asm3.sys> sys_slvs.py(68): dof remaining: 0
4.306618 <asm3.sys> sys_slvs.py(68): dof remaining: 0
16.509653 <asm3.sys> sys_slvs.py(68): dof remaining: 0
5.972761 <asm3.sys> sys_slvs.py(68): dof remaining: 0
6.713136 <asm3.sys> sys_slvs.py(68): dof remaining: 0
108.393437 <asm3.sys> sys_slvs.py(68): dof remaining: 0
11.415749 <asm3.sys> sys_slvs.py(68): dof remaining: 0
<TopoShape> assembly.py(764)|TopoShapeEx.cpp(1049): hasher mismatch
<TopoShape> assembly.py(764)|TopoShapeEx.cpp(1049): hasher mismatch
<TopoShape> assembly.py(764)|TopoShapeEx.cpp(1049): hasher mismatch
<TopoShape> assembly.py(764)|TopoShapeEx.cpp(1049): hasher mismatch
107.10417 <asm3.sys> sys_slvs.py(68): dof remaining: 0
16.525865 <asm3.sys> sys_slvs.py(68): dof remaining: 0
0.792698 <asm3.sys> sys_slvs.py(68): dof remaining: 0
0.030162 <asm3.sys> sys_slvs.py(68): dof remaining: 0
0.182596 <asm3.sys> sys_slvs.py(68): dof remaining: 3
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f4f68fe5210]
#1  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x67a1f8) [0x7f4f5e3271f8]
#2  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x302f01) [0x7f4f5dfaff01]
#3  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x30318e) [0x7f4f5dfb018e]
#4  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x1487eb) [0x7f4f5ddf57eb]
#5  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x39fef9) [0x7f4f5e04cef9]
#6  /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x3a02e2) [0x7f4f5e04d2e2]
#7  0x7f4f6b4b0b81 in SoFCVertexArrayIndexer::render(SoState*, cc_glglue const*, int, unsigned int, long const*, int const*, int) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x1d1
#8  0x7f4f6b4b399d in SoFCVertexCacheP::render(SoState*, SoFCVertexArrayIndexer*, int, long const*, int const*, int) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x40d
#9  0x7f4f6b4b3bb8 in SoFCVertexCache::renderLines(SoState*, int, int, bool) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x88
#10  0x7f4f6b4e14d3 in SoFCRendererP::renderOpaque(SoGLRenderAction*, std::vector<DrawEntry, std::allocator<DrawEntry> >&, std::vector<unsigned long, std::allocator<unsigned long> >&, int) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x453
#11  0x7f4f6b4e2578 in SoFCRenderer::render(SoGLRenderAction*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x668
#12  0x7f4f6b4d3f87 in SoFCRenderCacheManager::render(SoGLRenderAction*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x1d7
#13  0x7f4f6b5175ad in Gui::SoFCUnifiedSelection::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x15d
#14  0x7f4f68ba4245 in SoSeparator::GLRenderBelowPath(SoGLRenderAction*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0x3e5
#15  0x7f4f68979149 in SoAction::traverse(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0x69
#16  0x7f4f68980d96 in SoGLRenderAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0x186
#17  0x7f4f6b523df4 in Gui::SoBoxSelectionRenderAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x64
#18  0x7f4f6898041f in SoGLRenderActionP::renderSingle(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0xbf
#19  0x7f4f68980aae in SoGLRenderActionP::render(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0x11e
#20  0x7f4f68980cb2 in SoGLRenderAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0xa2
#21  0x7f4f6b523df4 in Gui::SoBoxSelectionRenderAction::beginTraversal(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x64
#22  0x7f4f68979e2a in SoAction::apply(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/../lib/libCoin.so.80+0x2ea
#23  0x7f4f6b52137a in Gui::SoBoxSelectionRenderAction::apply(SoNode*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x2a
#24  0x7f4f6b5ee224 in Gui::View3DInventorViewer::renderToFramebuffer(QOpenGLFramebufferObject*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x1a4
#25  0x7f4f6b5ee8f3 in Gui::View3DInventorViewer::imageFromFramebuffer(int, int, int, QColor const&, QImage&) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x113
#26  0x7f4f6b220849 in Gui::Thumbnail::SaveDocFile(Base::Writer&) const from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0xa9
#27  0x7f4f6a2533f0 in Base::ZipWriter::writeFiles() from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADBase.so+0x150
#28  0x7f4f6a57ce92 in App::Document::save(Base::Writer&, bool) const from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADApp.so+0x112
#29  0x7f4f6a58112a in App::Document::saveToFile(char const*) const from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADApp.so+0x47a
#30  0x7f4f6a581fd4 in App::Document::save() from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADApp.so+0x1f4
#31  0x7f4f6a5e1d34 in App::DocumentPy::save(_object*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADApp.so+0x44
#32  0x7f4f6a5e1e57 in App::DocumentPy::staticCallback_save(_object*, _object*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADApp.so+0x57
#33  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x163928) [0x7f4f6aaa0928]
#34  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x2df) [0x7f4f6aa6feaf]
#35  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x50fd) [0x7f4f6ab0287d]
#36  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x195489) [0x7f4f6aad2489]
#37  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f4f6ab6fb01]
#38  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f4f6ab6fb4a]
#39  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCode+0x1c) [0x7f4f6ab6fb6c]
#40  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x232c1f) [0x7f4f6ab6fc1f]
#41  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x256f8c) [0x7f4f6ab93f8c]
#42  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa7) [0x7f4f6ab94057]
#43  0x7f4f6a1e136c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADBase.so+0x6c
#44  0x7f4f6b258bc1 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x91
#45  0x7f4f6b258d61 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x101
#46  0x7f4f6b1d1c6b in Gui::Document::save() from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x2db
#47  0x7f4f6b7121d9 in Gui::MDIView::onMsg(char const*, char const**) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0xb9
#48  0x7f4f6b5d6a17 in Gui::View3DInventor::onMsg(char const*, char const**) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x327
#49  0x7f4f6b1626dd in Gui::Application::sendMsgToActiveView(char const*, char const**) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x3d
#50  0x7f4f6b18a2dd in Gui::Application::sSendActiveView(_object*, _object*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x6d
#51  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x163928) [0x7f4f6aaa0928]
#52  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x2df) [0x7f4f6aa6feaf]
#53  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x50fd) [0x7f4f6ab0287d]
#54  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x195489) [0x7f4f6aad2489]
#55  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x51) [0x7f4f6ab6fb01]
#56  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3a) [0x7f4f6ab6fb4a]
#57  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyEval_EvalCode+0x1c) [0x7f4f6ab6fb6c]
#58  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x232c1f) [0x7f4f6ab6fc1f]
#59  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(+0x256f8c) [0x7f4f6ab93f8c]
#60  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libpython3.9.so.1.0(PyRun_StringFlags+0xa7) [0x7f4f6ab94057]
#61  0x7f4f6a1e136c in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADBase.so+0x6c
#62  0x7f4f6b258bc1 in Gui::Command::_runCommand(char const*, int, Gui::Command::DoCmd_Type, char const*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x91
#63  0x7f4f6b258d61 in Gui::Command::_doCommand(char const*, int, Gui::Command::DoCmd_Type, char const*, ...) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x101
#64  0x7f4f6b261300 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x3e0
#65  0x7f4f694ffa18 in QMetaObject::activate(QObject*, int, int, void**) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Core.so.5+0x6c0
#66  0x7f4f69d0c928 in QAction::triggered(bool) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Widgets.so.5+0x32
#67  0x7f4f69d0e2b2 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Widgets.so.5+0xc6
#68  0x7f4f69d0ea3b in QAction::event(QEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Widgets.so.5+0xb3
#69  0x7f4f69d117f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Widgets.so.5+0xdc
#70  0x7f4f69d1731d in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Widgets.so.5+0x1ac9
#71  0x7f4f6b20f759 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x89
#72  0x7f4f694e9606 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Core.so.5+0x86
#73  0x7f4f698a5b51 in QShortcutMap::dispatchEvent(QKeyEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0xd5
#74  0x7f4f698a5bc2 in QShortcutMap::tryShortcut(QKeyEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0x5c
#75  0x7f4f6987dac0 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0xb0
#76  0x7f4f6988be4c in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0x6c
#77  0x7f4f6988e939 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0x79
#78  0x7f4f6987bc65 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Gui.so.5+0x63
#79  /tmp/.mount_FreeCAjFK0ie/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x5b010) [0x7f4f60262010]
#80  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_dispatch+0x27d) [0x7f4f65b7123d]
#81  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/./libglib-2.0.so.0(+0x554d1) [0x7f4f65b714d1]
#82  /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x31) [0x7f4f65b71571]
#83  0x7f4f695180e8 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Core.so.5+0x5e
#84  0x7f4f694e6019 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Core.so.5+0x187
#85  0x7f4f694e9e8f in QCoreApplication::exec() from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib/libQt5Core.so.5+0xfd
#86  0x7f4f6b188e1e in Gui::Application::runApplication() from /tmp/.mount_FreeCAjFK0ie/usr/bin/../lib64/libFreeCADGui.so+0x40e
#87  /tmp/.mount_FreeCAjFK0ie/usr/bin/FreeCADLink(+0x44be) [0x55daa2ea44be]
#88  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f4f68fc60b3]
#89  /tmp/.mount_FreeCAjFK0ie/usr/bin/FreeCADLink(+0x47d5) [0x55daa2ea47d5]
```

```
OS: KDE neon User Edition 5.22 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

**Comment by bennvan** [comment]
I don't know if it's from the same cause but I can reproduce a crash just by renaming a body and immediately saving after. This only happens when the experimental renderer is enabled. 

![Peek 2021-07-15 19-07](https://user-images.githubusercontent.com/44966500/125763661-d15b7d8c-65de-4239-9a19-5f7bca7d67b7.gif)

OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/Australia (en_AU)

**Comment by luzpaz** [comment]
@StudioPetrikas please retest on latest and report back. Thanks!

**Comment by StudioPetrikas** [comment]
> @StudioPetrikas please retest on latest and report back. Thanks!

Haven't had a crash since my last post here. Very stable here.

**Comment by luzpaz** [comment]
Thanks. Closing ticket. If re-appears, please re-open.
