### ISSUE TITLE
Assembly container exception

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#73]
# Description 
Creating a second assembly container throws the following exception: 

```
<asm3.main> 113.54074 - assembly.py(2529): solver exception when auto recompute
Traceback (most recent call last):
  File "/opt/FreeCAD/Ext/freecad/asm3/FCADLogger.py", line 83, in _catch
    return func(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 405, in solve
    return _solve(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 375, in _solve
    Solver(assembly,reportFailed,dragPart,recompute,rollback)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 65, in __init__
    self._fixedParts = Constraint.getFixedParts(self,cstrs,partGroup)
  File "/opt/FreeCAD/Ext/freecad/asm3/constraint.py", line 516, in getFixedParts
    for info in obj.Proxy.getElementsInfo():
  File "/opt/FreeCAD/Ext/freecad/asm3/assembly.py", line 1524, in getElementsInfo
    return [ e.Proxy.getInfo() for e in self.getElements() ]
  File "/opt/FreeCAD/Ext/freecad/asm3/assembly.py", line 1514, in getElements
    info = o.Proxy.getInfo()
  File "/opt/FreeCAD/Ext/freecad/asm3/assembly.py", line 1194, in getInfo
    self.getElementSubname(),shape=shape)
  File "/opt/FreeCAD/Ext/freecad/asm3/assembly.py", line 875, in getElementInfo
    objName(parent), subnameRef))
RuntimeError: Invalid sub-object "Parts001", Link005.Pocket.;#47;:M;CUT;:T4002:3:E.Edge18
```

![creating assembly container exception](https://user-images.githubusercontent.com/6639874/45226266-111ab880-b2c7-11e8-96cf-ae7e691c8dcd.gif)

# Version 

(current latest)

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14991 (Git)
Build type: Unknown
Branch: LinkStage3
Hash: ca6a60371470490c74b8d7bd967bf301b4253247
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)
```

# File 

[case-v3-20180907T1750.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2361494/case-v3-20180907T1750.zip)

**Comment by ceremcem** [comment]
It seems there was a side effect of a [previous hack](https://github.com/realthunder/FreeCAD_assembly3/issues/68#issuecomment-419341146), let's ignore this for now.
