### ISSUE TITLE
Exception: The graph must be a DAG

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#75]
I'm trying to create a sub-shape binder for an object inside an Assembly container, as if it was a regular part: 

![dag](https://user-images.githubusercontent.com/6639874/45244655-6ecbf680-b301-11e8-99dc-d18c64473222.gif)

```
Exception (Fri Sep  7 17:49:34 2018): Document::getDependencyList: The graph must be a DAG.  
<App::Document> Document.cpp(2849): Binder006 still touched after recompute
<App::Document> Document.cpp(2849): Relation008 still touched after recompute
<App::Document> Document.cpp(2849): Element033 still touched after recompute
<App::Document> Document.cpp(2849): ElementLink014 still touched after recompute
<App::Document> Document.cpp(2849): Constraint007 still touched after recompute
<App::Document> Document.cpp(2849): Relations still touched after recompute
<App::Document> Document.cpp(2849): ElementLink009 still touched after recompute
<App::Document> Document.cpp(2849): ElementLink003 still touched after recompute
<App::Document> Document.cpp(2849): Elements still touched after recompute
<App::Document> Document.cpp(2849): Element032 still touched after recompute
<App::Document> Document.cpp(2849): Assembly still touched after recompute
<App::Document> Document.cpp(2849): Relation001 still touched after recompute
<App::Document> Document.cpp(2849): Constraint still touched after recompute
<App::Document> Document.cpp(2849): Constraint005 still touched after recompute
<App::Document> Document.cpp(2849): Constraint006 still touched after recompute
<App::Document> Document.cpp(2849): Element still touched after recompute
<App::Document> Document.cpp(2849): ElementLink002 still touched after recompute
<App::Document> Document.cpp(2849): Element030 still touched after recompute
<App::Document> Document.cpp(2849): Element029 still touched after recompute
<App::Document> Document.cpp(2849): Relation003 still touched after recompute
<App::Document> Document.cpp(2849): Element028 still touched after recompute
<App::Document> Document.cpp(2849): Constraints still touched after recompute
Exception (Fri Sep  7 17:49:36 2018): Document::getDependencyList: The graph must be a DAG.  
<asm3.main> 84.707502 - assembly.py(2529): solver exception when auto recompute
Traceback (most recent call last):
  File "/opt/FreeCAD/Ext/freecad/asm3/FCADLogger.py", line 83, in _catch
    return func(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 405, in solve
    return _solve(*args,**kargs)
  File "/opt/FreeCAD/Ext/freecad/asm3/solver.py", line 353, in _solve
    objs = FreeCAD.getDependentObjects(assemblies,False,True)
FreeCADError: FreeCAD exception thrown (Document::getDependencyList: The graph must be a DAG.)
```

If I insist trying it to create directly under the target (active) Body, there is no error thrown, which in turns gives the feeling that it is somehow related with #74 

![no-dag](https://user-images.githubusercontent.com/6639874/45244752-e0a44000-b301-11e8-8bb1-9a8433305b52.gif)

**Comment by ceremcem** [comment]
Note to myself: [Fix the Binder source manually.](https://github.com/realthunder/FreeCAD_assembly3/issues/74#issuecomment-419613593)
