### ISSUE TITLE
after using tools->preset configurations->overlay light theme FC crashes after startup

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#859]
When I change the Display settings with `tools->preset configurations->overlay light theme` the next start of FC gives a `Program received signal SIGSEGV, Segmentation fault.`

Complete error message after the restart:
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60) [0x7fbf2c9b4d60]
#1  0x7fbf3170789c in std::vector<Gui::TaskView::TaskWatcher*, std::allocator<Gui::TaskView::TaskWatcher*> >::size() const from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0xc
#2  0x7fbf31705e22 in Gui::TaskView::TaskView::onUpdateWatcher() from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0x66
#3  /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so(+0x1908f78) [0x7fbf31706f78]
#4  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e45e0) [0x7fbf2d0095e0]
#5  0x7fbf2d00d4ba in QTimer::timeout(QTimer::QPrivateSignal) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x3a
#6  0x7fbf2cffef2f in QObject::event(QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x1cf
#7  0x7fbf2da9715f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x7f
#8  0x7fbf312025ad in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0xff
#9  0x7fbf2cfd2fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x12a
#10  0x7fbf2d0298e3 in QTimerInfoList::activateTimers() from /lib/x86_64-linux-gnu/libQt5Core.so.5+0x3e3
#11  /lib/x86_64-linux-gnu/libQt5Core.so.5(+0x305164) [0x7fbf2d02a164]
#12  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x25b) [0x7fbf2adb0e6b]
#13  /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x52118) [0x7fbf2adb1118]
#14  /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2f) [0x7fbf2adb11cf]
#15  0x7fbf2d02a590 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib/x86_64-linux-gnu/libQt5Core.so.5+0xd0
#16  0x7fbf3192b4ea in Gui::SplashObserver::Log(char const*) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0x202
#17  0x7fbf3192b2e5 in Gui::SplashObserver::SendLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Base::LogStyle) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0x37
#18  0x7fbf2e7d4495 in Base::ConsoleSingleton::NotifyLog(char const*) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADBase.so+0xbb
#19  0x7fbf2e7d5a60 in Base::ConsoleSingleton::sPyLog(_object*, _object*) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADBase.so+0xe2
#20  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x10cc74) [0x7fbf2e0cac74]
#21  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyObject_MakeTpCall+0x90) [0x7fbf2e084a50]
#22  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x7248) [0x7fbf2e034f08]
#23  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x6f033) [0x7fbf2e02d033]
#24  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyEval_EvalFrameDefault+0x6456) [0x7fbf2e034116]
#25  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x1a4ddc) [0x7fbf2e162ddc]
#26  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(_PyEval_EvalCodeWithName+0x4e) [0x7fbf2e16312e]
#27  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyEval_EvalCodeEx+0x3e) [0x7fbf2e16317e]
#28  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyEval_EvalCode+0x1b) [0x7fbf2e15e72b]
#29  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(+0x1e9735) [0x7fbf2e1a7735]
#30  /lib/x86_64-linux-gnu/libpython3.9.so.1.0(PyRun_StringFlags+0x93) [0x7fbf2e1a8013]
#31  0x7fbf2e7ef72a in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADBase.so+0xd2
#32  0x7fbf310b53c3 in Gui::Application::runInitGuiScript() from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0x37
#33  0x7fbf310b73b6 in Gui::postMainWindowSetup(Gui::MainWindow&) from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0xd42
#34  0x7fbf310b86c6 in Gui::Application::runApplication() from /home/ton/FREECAD/daily/freecad/lib/libFreeCADGui.so+0x452
#35  /home/ton/FREECAD/daily/freecad/bin/FreeCAD(+0x9167) [0x55f3b8836167]
#36  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea) [0x7fbf2c99fd0a]
#37  /home/ton/FREECAD/daily/freecad/bin/FreeCAD(+0x84da) [0x55f3b88354da]
```

After removing the ~/.Freecad directory I can use FC again (but in boring colors and a very antiquated layout)

```
OS: Debian GNU/Linux 11 (bullseye) (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28505 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: 5aefd3c9ec304ff3f95dbe59e7d2ca46691bc9d5
Python version: 3.9.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United States (en_US)
```

**Comment by snelweg** [comment]
Oops, I got the newest Daily git pull now and the problem seems to be gone.

```
OS: Debian GNU/Linux 11 (bullseye) (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.28512 (Git)
Build type: Unknown
Branch: LinkDaily
Hash: 9b6e9d5a86f6d726ba9811719c8915dad20c9790
Python version: 3.9.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United States (en_US)

```
