### ISSUE TITLE
Path 3D Pocket does not work on OSX

### ISSUE THREAD

**Issue by sparkks** [realthunder/FreeCAD_assembly3#879]
When trying to create Path 3D pocket error is displayed :
```
_21:59:29  Traceback (most recent call last):
  File "/Users/macbook/Desktop/FCD/FreeCAD_10.15_stable.app/Contents/Resources/Mod/Path/PathScripts/PathUtils.py", line 60, in new_function
    res = function(*args, **kwargs)
  File "/Users/macbook/Desktop/FCD/FreeCAD_10.15_stable.app/Contents/Resources/Mod/Path/PathScripts/PathOp.py", line 552, in execute
    result = self.opExecute(obj)  # pylint: disable=assignment-from-no-return
  File "/Users/macbook/Desktop/FCD/FreeCAD_10.15_stable.app/Contents/Resources/Mod/Path/PathScripts/PathAreaOp.py", line 347, in opExecute
    for shape, isHole, sub in shapes:
<class 'ValueError'>: too many values to unpack (expected 3)
21:59:29  Recompute failed! Please check report view._
```
OS: macOS Catalina 10.15.7
FreeCAD: OS: macOS 10.15
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +3962 (Git)
Build type: Release
Branch: LinkStage3
Hash: c6cb39697eb439caf7e5bd0208ca3082a7820547
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: C/Default (C)

![Screenshot 2021-10-15 at 22 06 49](https://user-images.githubusercontent.com/31029909/137539872-efa7b72d-4e4c-409d-bc5a-bb1daf72b3e0.png)
![Screenshot 2021-10-15 at 22 05 30](https://user-images.githubusercontent.com/31029909/137539937-a26c2d30-6635-4797-be59-123281ed33c6.png)

[path_3Dpocket_error.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7355495/path_3Dpocket_error.FCStd.zip)

![Screenshot 2021-10-15 at 22 05 47](https://user-images.githubusercontent.com/31029909/137539921-f5714a60-3f3a-432c-956e-af0b4ea4f487.png)

**Comment by triman** [comment]
This has been fixed in the main FreeCAD branch: https://github.com/FreeCAD/FreeCAD/pull/4901

**Comment by luzpaz** [comment]
@sparkks can you still recreate this on latest LinkDaily version?

**Comment by nyquist2205** [comment]
I just ran into this exact error with the latest LinkDaily version, so yes, this still seems to be an issue. In the official weekly build this seems to be resolved, could not recreate it there.

![Unbenannt](https://user-images.githubusercontent.com/47365194/155861036-d1a8305c-e5e7-4542-89c4-2301ec99abe8.PNG)

Error occured with:
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.118.30769 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3b620b713e24c9637db8ea6ad1f1ee88ef13367a
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: German/Germany (de_DE)

Error did not occur with:
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.27518 (Git)
Build type: Release
Python version: 3.8.12
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: German/Germany (de_DE)

**Comment by Nokse22** [comment]
Same thing happens in linux
